# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userform.ui'
#
# Created: Wed Jun 06 22:41:16 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(500, 640)
        Dialog.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setMargin(9)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textBrowser = QStatusBrowser(Dialog)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFollow = QtGui.QWidget()
        self.tabFollow.setObjectName(_fromUtf8("tabFollow"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabFollow)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelFollows = QtGui.QLabel(self.tabFollow)
        self.labelFollows.setObjectName(_fromUtf8("labelFollows"))
        self.horizontalLayout.addWidget(self.labelFollows)
        self.labelFollowedBy = QtGui.QLabel(self.tabFollow)
        self.labelFollowedBy.setObjectName(_fromUtf8("labelFollowedBy"))
        self.horizontalLayout.addWidget(self.labelFollowedBy)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.stackedWidgetFollower = QtGui.QStackedWidget(self.tabFollow)
        self.stackedWidgetFollower.setObjectName(_fromUtf8("stackedWidgetFollower"))
        self.pageFollows = QtGui.QWidget()
        self.pageFollows.setObjectName(_fromUtf8("pageFollows"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pageFollows)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.listWidgetFollows = QtGui.QListWidget(self.pageFollows)
        self.listWidgetFollows.setObjectName(_fromUtf8("listWidgetFollows"))
        self.verticalLayout_3.addWidget(self.listWidgetFollows)
        self.stackedWidgetFollower.addWidget(self.pageFollows)
        self.pageFollowedBy = QtGui.QWidget()
        self.pageFollowedBy.setObjectName(_fromUtf8("pageFollowedBy"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pageFollowedBy)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.listWidgetFollowedBy = QtGui.QListWidget(self.pageFollowedBy)
        self.listWidgetFollowedBy.setObjectName(_fromUtf8("listWidgetFollowedBy"))
        self.verticalLayout_6.addWidget(self.listWidgetFollowedBy)
        self.stackedWidgetFollower.addWidget(self.pageFollowedBy)
        self.verticalLayout_2.addWidget(self.stackedWidgetFollower)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resource/illvelo-32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabFollow, icon, _fromUtf8(""))
        self.tabList = QtGui.QWidget()
        self.tabList.setObjectName(_fromUtf8("tabList"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabList)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelLists = QtGui.QLabel(self.tabList)
        self.labelLists.setObjectName(_fromUtf8("labelLists"))
        self.horizontalLayout_2.addWidget(self.labelLists)
        self.labelListedBy = QtGui.QLabel(self.tabList)
        self.labelListedBy.setObjectName(_fromUtf8("labelListedBy"))
        self.horizontalLayout_2.addWidget(self.labelListedBy)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.stackedWidgetList = QtGui.QStackedWidget(self.tabList)
        self.stackedWidgetList.setObjectName(_fromUtf8("stackedWidgetList"))
        self.pageLists = QtGui.QWidget()
        self.pageLists.setObjectName(_fromUtf8("pageLists"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pageLists)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.listWidgetLists = QtGui.QListWidget(self.pageLists)
        self.listWidgetLists.setObjectName(_fromUtf8("listWidgetLists"))
        self.verticalLayout_4.addWidget(self.listWidgetLists)
        self.stackedWidgetList.addWidget(self.pageLists)
        self.pageListedBy = QtGui.QWidget()
        self.pageListedBy.setObjectName(_fromUtf8("pageListedBy"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pageListedBy)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.listWidgetListedBy = QtGui.QListWidget(self.pageListedBy)
        self.listWidgetListedBy.setObjectName(_fromUtf8("listWidgetListedBy"))
        self.verticalLayout_7.addWidget(self.listWidgetListedBy)
        self.stackedWidgetList.addWidget(self.pageListedBy)
        self.verticalLayout_5.addWidget(self.stackedWidgetList)
        self.tabWidget.addTab(self.tabList, icon, _fromUtf8(""))
        self.tabFav = QtGui.QWidget()
        self.tabFav.setObjectName(_fromUtf8("tabFav"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabFav)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textBrowserFav = QStatusBrowser(self.tabFav)
        self.textBrowserFav.setOpenLinks(False)
        self.textBrowserFav.setObjectName(_fromUtf8("textBrowserFav"))
        self.verticalLayout.addWidget(self.textBrowserFav)
        self.tabWidget.addTab(self.tabFav, icon, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidgetFollower.setCurrentIndex(1)
        self.stackedWidgetList.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.textBrowser, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.listWidgetFollowedBy)
        Dialog.setTabOrder(self.listWidgetFollowedBy, self.listWidgetLists)
        Dialog.setTabOrder(self.listWidgetLists, self.textBrowserFav)
        Dialog.setTabOrder(self.textBrowserFav, self.listWidgetFollows)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "{screen_name} - とにかくシンプルな Twitter クライアント", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFollows.setText(QtGui.QApplication.translate("Dialog", "{follows} 人をフォロー", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFollowedBy.setText(QtGui.QApplication.translate("Dialog", "{followed-by} 人がフォロー", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFollow), QtGui.QApplication.translate("Dialog", "フォロー", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLists.setText(QtGui.QApplication.translate("Dialog", "公開リスト数 {lists}", None, QtGui.QApplication.UnicodeUTF8))
        self.labelListedBy.setText(QtGui.QApplication.translate("Dialog", "{listed-by} 個のリストにいる", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabList), QtGui.QApplication.translate("Dialog", "リスト", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFav), QtGui.QApplication.translate("Dialog", "Favorites", None, QtGui.QApplication.UnicodeUTF8))

from qstatusbrowser import QStatusBrowser
import twclient_rc
